version: "2"
services:
  selenium-hub:    
    image: selenium/hub
    privileged: true
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    ports:
	  - "4444:4444"      
  chrome:
    image: selenium/node-chrome-debug
    shm_size: 2G
    privileged: true
    depends_on:
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_SESSIONS=2
      - NODE_MAX_INSTANCES=2
    volumes:
      - /dev/shm:/dev/shm
  firefox:    
    image: selenium/node-firefox-debug
    shm_size: 2G
    privileged: true
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_SESSIONS=2
      - NODE_MAX_INSTANCES=2
    volumes:
      - /dev/shm:/dev/shm
  uiTestFirefox:    
    image: smileys009/selenium-docker-linux
    privileged: true
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=selenium-hub
      - MODULE=dockering.xml
    volumes:
      - ./output/firefox:/usr/share/udemy/test-output
  uiTestChrome:
    image: smileys009/selenium-docker-linux
    privileged: true
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
      - MODULE=dockering.xml
    volumes:
      - ./output/chrome:/usr/share/udemy/test-output