version: "2"
services:
  selenium-hub:    
    image: selenium/hub
    networks: 
      - spring7
    privileged: true
  chrome:
    image: selenium/node-chrome-debug
    shm_size: '2gb'
    networks: 
      - spring7
    privileged: true
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    volumes:
      - /home/qa/Downloads:/home/seluser/Downloads/picsUpload/
  firefox:    
    image: selenium/node-firefox-debug
    shm_size: '2gb'
    networks: 
      - spring7
    privileged: true
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    volumes:
      - /home/qa/Downloads:/home/seluser/Downloads/picsUpload/
  uiTestFirefox:    
    image: smileys009/selenium-docker-linux
    networks: 
      - spring7
    privileged: true
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=selenium-hub
      - MODULE=dockering.xml
    volumes:
      - ./output/firefox:/usr/share/udemy/test-output
  uiTestChrome:
    image: smileys009/selenium-docker-linux
    networks: 
      - spring7
    privileged: true
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
      - MODULE=dockering.xml
    volumes:
      - ./output/chrome:/usr/share/udemy/test-output
networks:
  spring7:
    external: true