version: "3"
services:
  selenium-hub:
    image: selenium/hub
  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    volumes:
      - /dev/shm:/dev/shm
  firefox:
    image: selenium/node-firefox-debug
    shm_size: '1gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    volumes:
      - /dev/shm:/dev/shm
  dockering2:
    image: smileys009/selenium-docker-linux
    depends_on:
      - chrome
      - firefox
    environment:shm
      - BROWSER=firefox
      - HUB_HOST=selenium-hub
      - MODULE=dockering.xml
    volumes:
      - ./output/firefox:/usr/share/udemy/test-output
  dockering1:
    image: smileys009/selenium-docker-linux
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
      - MODULE=dockering.xml
    volumes:
      - ./output/chrome:/usr/share/udemy/test-output      