version: "3"
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
  firefox:
    image: selenium/node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
  dockering2:
    image: jarcibal/selenium-docker-linux
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=selenium-hub
      - MODULE=dockering.xml
    volumes:
      - ./resulta/firefox:/usr/share/udemy/test-output
  dockering1:
    image: jarcibal/selenium-docker-linux
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
      - MODULE=dockering.xml
    volumes:
      - ./resulta/chrome:/usr/share/udemy/test-output
